import { Document, Page, View, Text, StyleSheet, Font } from "@react-pdf/renderer";
import React from "react";

const styles = StyleSheet.create({
  page: {
    paddingTop: 56,
    paddingBottom: 56,
    paddingHorizontal: 56,
    fontFamily: "Helvetica",
    fontSize: 9,
    color: "#1E293B",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-end",
    marginBottom: 8,
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: "#0F172A",
  },
  headerBrand: {
    fontSize: 14,
    fontFamily: "Helvetica-Bold",
    color: "#0F172A",
  },
  headerRight: {
    alignItems: "flex-end",
  },
  headerTitle: {
    fontSize: 10,
    fontFamily: "Helvetica-Bold",
    color: "#0F172A",
  },
  headerDate: {
    fontSize: 8,
    color: "#64748B",
    marginTop: 2,
  },
  footer: {
    position: "absolute",
    bottom: 30,
    left: 56,
    right: 56,
    flexDirection: "row",
    justifyContent: "space-between",
    borderTopWidth: 1,
    borderTopColor: "#CBD5E1",
    paddingTop: 6,
  },
  footerText: {
    fontSize: 7,
    color: "#94A3B8",
  },
  sectionTitle: {
    backgroundColor: "#F1F5F9",
    paddingVertical: 5,
    paddingHorizontal: 8,
    marginTop: 14,
    marginBottom: 8,
  },
  sectionTitleText: {
    fontSize: 11,
    fontFamily: "Helvetica-Bold",
    color: "#0F172A",
  },
  tableHeader: {
    flexDirection: "row",
    backgroundColor: "#0F172A",
    paddingVertical: 5,
    paddingHorizontal: 4,
  },
  tableHeaderCell: {
    fontSize: 8,
    fontFamily: "Helvetica-Bold",
    color: "#FFFFFF",
  },
  tableRow: {
    flexDirection: "row",
    paddingVertical: 4,
    paddingHorizontal: 4,
    borderBottomWidth: 1,
    borderBottomColor: "#E2E8F0",
  },
  tableRowAlt: {
    backgroundColor: "#F8FAFC",
  },
  tableCell: {
    fontSize: 8,
    color: "#1E293B",
  },
  watermark: {
    position: "absolute",
    top: "45%",
    left: "15%",
    fontSize: 48,
    color: "#E2E8F0",
    transform: "rotate(-30deg)",
    fontFamily: "Helvetica-Bold",
    opacity: 0.3,
  },
});

export const PdfStyles = styles;

interface PdfHeaderProps {
  reportTitle: string;
  generationDate: string;
}

export function PdfHeader({ reportTitle, generationDate }: PdfHeaderProps) {
  return (
    <View style={styles.header} fixed>
      <Text style={styles.headerBrand}>CorpSync</Text>
      <View style={styles.headerRight}>
        <Text style={styles.headerTitle}>{reportTitle}</Text>
        <Text style={styles.headerDate}>Generated: {generationDate}</Text>
      </View>
    </View>
  );
}

export function PdfFooter() {
  return (
    <View style={styles.footer} fixed>
      <Text style={styles.footerText}>Confidential — Generated by CorpSync</Text>
      <Text
        style={styles.footerText}
        render={({ pageNumber, totalPages }) => `Page ${pageNumber} of ${totalPages}`}
      />
    </View>
  );
}

export function PdfSection({ title }: { title: string }) {
  return (
    <View style={styles.sectionTitle}>
      <Text style={styles.sectionTitleText}>{title}</Text>
    </View>
  );
}

interface PdfTableProps {
  columns: { label: string; width: string }[];
  rows: string[][];
}

export function PdfTable({ columns, rows }: PdfTableProps) {
  return (
    <View>
      <View style={styles.tableHeader}>
        {columns.map((col, i) => (
          <Text key={i} style={[styles.tableHeaderCell, { width: col.width }]}>
            {col.label}
          </Text>
        ))}
      </View>
      {rows.map((row, rowIdx) => (
        <View
          key={rowIdx}
          style={[styles.tableRow, rowIdx % 2 === 1 ? styles.tableRowAlt : {}]}
        >
          {row.map((cell, cellIdx) => (
            <Text key={cellIdx} style={[styles.tableCell, { width: columns[cellIdx]?.width || "auto" }]}>
              {cell || "[Not recorded]"}
            </Text>
          ))}
        </View>
      ))}
    </View>
  );
}

interface PdfPageWrapperProps {
  reportTitle: string;
  generationDate: string;
  isHistorical?: boolean;
  children: React.ReactNode;
}

export function PdfPageWrapper({ reportTitle, generationDate, isHistorical, children }: PdfPageWrapperProps) {
  return (
    <Page size="A4" style={styles.page}>
      <PdfHeader reportTitle={reportTitle} generationDate={generationDate} />
      {isHistorical && <Text style={styles.watermark}>HISTORICAL SNAPSHOT</Text>}
      {children}
      <PdfFooter />
    </Page>
  );
}
