import { corsFor, requireInternalAuth } from "../_shared/http.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.49.1";

Deno.serve(async (req: Request) => {
  const corsHeaders = corsFor(req);
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  // Scheduled job: operates across all workspaces with the service role.
  const denied = await requireInternalAuth(req, corsHeaders);
  if (denied) return denied;

  try {
    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const serviceRoleKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const resendApiKey = Deno.env.get("RESEND_API_KEY");
    const supabase = createClient(supabaseUrl, serviceRoleKey);

    const { data: workspaces } = await supabase.from("workspaces").select("id, name");
    if (!workspaces?.length) {
      return new Response(JSON.stringify({ message: "No workspaces" }), {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const today = new Date().toISOString().split("T")[0];
    let totalCreated = 0;

    for (const ws of workspaces) {
      const { data: rules } = await supabase
        .from("alert_rules")
        .select("*")
        .eq("workspace_id", ws.id)
        .eq("is_active", true)
        .eq("rule_type", "MOVEMENT_DRAFT_PENDING");

      if (!rules?.length) continue;

      const { data: adminRoles } = await supabase
        .from("user_roles")
        .select("user_id")
        .eq("workspace_id", ws.id)
        .eq("role", "admin");

      const adminUserIds = (adminRoles || []).map((r: any) => r.user_id);
      const { data: adminProfiles } = adminUserIds.length > 0
        ? await supabase.from("profiles").select("id, email, user_id").in("user_id", adminUserIds)
        : { data: [] };

      for (const rule of rules) {
        const thresholdDays = rule.threshold_days || 7;
        const cutoffDate = new Date();
        cutoffDate.setDate(cutoffDate.getDate() - thresholdDays);

        const { data: drafts } = await supabase
          .from("movements")
          .select("*, company:entities!movements_company_entity_id_fkey(name)")
          .eq("workspace_id", ws.id)
          .eq("status", "draft")
          .lte("created_at", cutoffDate.toISOString());

        if (!drafts?.length) continue;

        for (const draft of drafts) {
          // Duplicate check
          const { data: existing } = await supabase
            .from("notifications")
            .select("id")
            .eq("movement_id", draft.id)
            .eq("notification_type", "MOVEMENT_DRAFT_PENDING")
            .gte("created_at", today + "T00:00:00Z")
            .lte("created_at", today + "T23:59:59Z")
            .limit(1);

          if (existing?.length) continue;

          const daysAgo = Math.ceil((Date.now() - new Date(draft.created_at).getTime()) / (1000 * 60 * 60 * 24));
          const companyName = (draft.company as any)?.name || "Unknown";
          const title = `Draft pending: ${draft.movement_type?.replace(/_/g, " ")} — ${companyName}`;
          const body = `A ${draft.movement_type?.replace(/_/g, " ")} movement for ${companyName} has been saved as draft for ${daysAgo} days. Reference: ${draft.reference_number || "No reference"}. Please review and confirm or delete.`;

          for (const profile of (adminProfiles || [])) {
            await supabase.from("notifications").insert({
              workspace_id: ws.id,
              recipient_user_id: profile.id,
              notification_type: "MOVEMENT_DRAFT_PENDING",
              title,
              body,
              movement_id: draft.id,
              action_url: `/ledger/${draft.id}`,
            });
            totalCreated++;
          }

          // Send email
          if (rule.notify_email && resendApiKey) {
            const emails = [
              ...(adminProfiles || []).map((p: any) => p.email).filter(Boolean),
              ...(rule.additional_emails || []),
            ];
            const senderEmail = rule.sender_email || "onboarding@resend.dev";

            for (const email of emails) {
              try {
                await fetch("https://api.resend.com/emails", {
                  method: "POST",
                  headers: {
                    "Content-Type": "application/json",
                    Authorization: `Bearer ${resendApiKey}`,
                  },
                  body: JSON.stringify({
                    from: `CorpSync <${senderEmail}>`,
                    to: [email],
                    subject: `[Reminder] Pending Draft Movement — ${companyName} — CorpSync`,
                    html: `<h2>${title}</h2><p>${body}</p><hr /><p style="color:#666;">This alert was generated by CorpSync on behalf of ${ws.name}.</p>`,
                    text: body,
                  }),
                });
              } catch (err) {
                console.error("Email send failed:", err);
              }
            }
          }
        }
      }
    }

    return new Response(
      JSON.stringify({ message: "Draft movement check complete", notifications: totalCreated }),
      { headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  } catch (err) {
    console.error("check-draft-movements error:", err);
    return new Response(JSON.stringify({ error: String(err) }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
